### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by kgryte** [dstructs/cast-arrays#1]
Small utility to cast an `array` from one data type to an `array` of a different data type. Effectively does a copy-by-value. Supports `array-like` objects, although best **not** to use to cast `arguments` to an `array`. 

Relies on both [compute-array-constructors](https://github.com/compute-io/array-constructors) and [compute-array-dtypes](https://github.com/compute-io/array-dtypes) being published before being publishable.

**Comment by Planeshifter** [comment]
Looks good to me now. Publish?

**Comment by kgryte** [comment]
Done.
